# Generated by Django 5.1.5 on 2025-01-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudapp', '0002_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='contenido',
            new_name='content',
        ),
    ]
