# Generated by Django 5.1.5 on 2025-01-17 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudapp', '0003_rename_contenido_notas_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycrudapp.users'),
            preserve_default=False,
        ),
    ]
