# Generated by Django 5.1.5 on 2025-01-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudapp', '0004_notas_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Notes',
        ),
    ]
