# Generated by Django 5.1.5 on 2025-01-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='projecy',
            new_name='project',
        ),
    ]
